# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-30 21:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='date',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 6, 30, 21, 15, 56, 116659, tzinfo=utc), verbose_name='date published'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rating',
            name='rate',
            field=models.IntegerField(default=5),
        ),
    ]
