# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-30 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20160701_0145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
