# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-30 21:33
from __future__ import unicode_literals

from django.db import migrations
import website.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20160701_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rate',
            field=website.models.RateField(),
        ),
    ]
