# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-30 21:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20160701_0203'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='type',
            field=models.CharField(default='restaurant', max_length=20),
            preserve_default=False,
        ),
    ]
