# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_place_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='url',
            field=models.CharField(default='tehran-oonja', max_length=130, unique=True),
            preserve_default=False,
        ),
    ]
