# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 08:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_place_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='url',
            new_name='uri',
        ),
    ]
