# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 15:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20160701_1240'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='rating',
            new_name='Review',
        ),
    ]
